- hosts: mc
  become: yes

  tasks:
    - name: Install Java
      yum:
        name: java-21-amazon-corretto-headless


    - name: Server directory
      file:
        path: /opt/minecraft/server
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'


    - name: Download minecraft server from mojang
      get_url:
        url: https://piston-data.mojang.com/v1/objects/e6ec2f64e6080b9b5d9b471b291c33cc7f509733/server.jar
        dest: /opt/minecraft/server/server.jar
        owner: ec2-user
        mode: '0755'


    - name: Bypass EULA Accept
      copy:
        dest: /opt/minecraft/server/eula.txt
        content: "eula=true\n"
        owner: ec2-user


    - name: Use the log4j2.xml file for logging correctly
      copy:
        src: log4j2.xml
        dest: /opt/minecraft/server/log4j2.xml
        owner: ec2-user


    - name: Start script
      copy:
        dest: /usr/local/bin/minecraft-start
        content: |
          #!/bin/bash
          java -Xmx1G -Xms1G -Dlog4j.configurationFile=/opt/minecraft/server/log4j2.xml -jar server.jar nogui
        owner: ec2-user
        mode: '0755'


    - name: Stop script
      copy:
        dest: /usr/local/bin/minecraft-stop
        content: |
          #!/bin/bash
          kill -9 $(ps -ef | pgrep -f "java")
        owner: ec2-user
        mode: '0755'


    - name: Create Minecraft service within systemd
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft
          Wants=network-online.target
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/opt/minecraft/server
          ExecStart=/usr/local/bin/minecraft-start
          Restart=always

          [Install]
          WantedBy=multi-user.target
      mode: '0644'


    - name: Reload & enable service
      systemd:
        daemon_reload: yes
        name: minecraft
        enabled: yes
        state: started
